version: '3.7'

services:
  myapp:
    environment:
      PYTHONUNBUFFERED: 1
      LOGLEVEL: INFO
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./data:/data
    ports:
      - 5000:5000
    networks:
      - my_network
  worker:
    environment:
      PYTHONUNBUFFERED: 1
      LOGLEVEL: INFO
    build:
      context: ./worker
      dockerfile: Dockerfile
    ports:
      - 5001:5000
    networks:
      - my_network
  redis:
    image: 'redis:5.0.6-alpine'
    command: redis-server
    ports:
      - '6379:6379'
    networks:
      - my_network

networks:
  my_network:
    external: true
